# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook_name', models.CharField(blank=True, max_length=200, null=True)),
                ('override_name', models.CharField(blank=True, max_length=200, null=True)),
                ('added_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('override_name', 'facebook_name'),
            },
        ),
    ]
