# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendtrack', '0002_auto_20180821_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friendtrack.Category'),
        ),
    ]
