# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smelltest.Scent')),
            ],
        ),
    ]
