# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smelltest', '0002_auto_20180116_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
