# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-24 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smelltest', '0006_auto_20180118_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scent',
            options={'ordering': ['id']},
        ),
    ]
