# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Failed'), (2, 'Cancelled'), (3, 'Completed')], default=0),
        ),
    ]
