# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0002_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
