# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 19:53
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0003_action_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(blank=True),
        ),
    ]
