# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0004_action_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Failed'), (2, 'Cancelled'), (3, 'Completed')])),
                ('start_at', models.DateTimeField(blank=True)),
                ('due_at', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionrecurrence',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtd.Action'),
        ),
    ]
