# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0009_auto_20170710_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='dependencies',
            field=models.ManyToManyField(related_name='depends_on', to='gtd.Action'),
        ),
    ]
