# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0010_action_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecurrence',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='depends_on', to='gtd.Action'),
        ),
    ]
