# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-20 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gtd', '0012_context_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actions',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions_owner',
                                      to='gtd.Folder')),
                ('bin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bin_owner',
                                             to='gtd.Folder')),
                ('collectbox',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collectbox_owner',
                                      to='gtd.Folder')),
                ('someday',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='someday_owner',
                                      to='gtd.Folder')),
                ('tickler',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickler_owner',
                                      to='gtd.Folder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gtd_user',
                                              to=settings.AUTH_USER_MODEL)),
                ('waiting_for',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waitingfor_owner',
                                      to='gtd.Folder')),
            ],
        ),
    ]
