# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0014_folder_special_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='context',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='gtd.Context'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='folder',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='gtd.Folder'),
            preserve_default=False,
        ),
    ]
